### PR TITLE
Navbar_Issue_Fixed

### PR DESCRIPTION
**Pull request by Jimmy-Taravia2001**
I Have fixed issue #73 using basic CSS formalities and updating the src file in your repository. Do tell me if the issue is solved or not after cross-checking in different devices.  Hope it helped your project. 
Drop a comment if it worked.

### CODE REVIEW

**Comment by Jimmy-Taravia2001** [comment]
Here is a screen-recorded snapshot of the website:

 

https://user-images.githubusercontent.com/79863205/194712853-1ffc778f-6243-4a8f-ac80-149978f787f8.mp4

**Comment by Ngoakor12** [comment]
It looks fine via the desktop while simulating a mobile device, but it's still the same story on the android chrome app. See video:
Uploading 2022_10_08_20_21_40.mp4 …

Let me know if you still want another crack at it, otherwise thanks for trying

If you're planning on trying it again I have a sneaky feeling using the `position: sticky` instead of the `position: fixed` I was using and `position: absolute you're using might work

**Comment by Jimmy-Taravia2001** [comment]
Hey @Ngoakor12 , I saw the same thing actually. But if you open that link in phone, what is happening is by default the screen is a little bit zoomed in. So if you zoom out from that screen size and then try it, the navbar won't hide on sccroll. Still if it doesn't happen, I will try to find what styling properties are causinng it or what type of different properties are having a conflict that is creating it.
For now, I would say try to open the link in phone and make screen fit by zooming out first, and tell me if it works.

**Comment by Ngoakor12** [comment]
Nice work detective :sweat_smile: 

The zoom out works great, but it needs to not be zoomed in by default. [This link](https://stackoverflow.com/questions/14272420/webpage-starts-zoomed-in-on-mobile-devices) seems to have an answer, check it out if you want still want to carry this through.

**Comment by Jimmy-Taravia2001** [comment]
Hello, I have made new changes with new CSS properties. After this pull request i will cross check and tell you if it is workinng correct way or not.

**Comment by Jimmy-Taravia2001** [comment]
It worked in my phone actually. Please recheck in your device. and tell me if it works.

**Review by Ngoakor12 — APPROVED** [review]
Magic :ok_hand:  :sweat_smile:

**Comment by Ngoakor12** [comment]
Thank you for taking the time to contribute :)

**Comment by Jimmy-Taravia2001** [comment]
I am quite a Nice Detective. :stuck_out_tongue_winking_eye:

**Pull request merged**
